spring:
  profiles:
    active: dev
  devtools:
    restart:
      additional-paths: src/main/java
  freemarker:
    settings:
      template_update_delay: 0
  aop:
    proxy-target-class: true  #需要使用CGLIB来实现AOP的时候